# Generated by Django 5.2.13 on 2026-04-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('familiya', models.CharField(max_length=100, verbose_name='Familiya')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('tug_sanasi', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('jins', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], default='erkak', max_length=10, verbose_name='Jins')),
                ('manzil', models.TextField(blank=True, verbose_name='Manzil')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('guruh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.guruh', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'ordering': ['familiya', 'ism'],
            },
        ),
    ]
