# Generated by Django 5.2.13 on 2026-04-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guruh',
            options={},
        ),
        migrations.AddField(
            model_name='guruh',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='guruhlar/'),
        ),
        migrations.AlterField(
            model_name='guruh',
            name='nomi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guruh',
            name='tavsif',
            field=models.TextField(blank=True),
        ),
    ]
